server:
  port: 9006

spring:
  application:
    name: cloud-nacos-payment-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ze1bw0,7E[9V
    url: jdbc:mysql://172.16.0.185:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wei.springcloud.entities
