server:
  port: 5555

spring:
  profiles:
    active: dev
  application:
    name: cloud-txlcn-client5555
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ze1bw0,7E[9V
    url: jdbc:mysql://172.16.0.185:3306/tx-service5555?useUnicode=true&characterEncoding=utf-8&useSSL=false
  redis:
    host: 172.16.0.185
    port: 6379
    password: Idss[2048]

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
