server:
  port: 80

spring:
  application:
    name: cloud-feign-consumer-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ze1bw0,7E[9V
    url: jdbc:mysql://192.168.59.131:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #高可用版
  instance:
    instance-id: consumer80
    prefer-ip-address: true
    #修改客户端向服务端发送心跳的周期时间（默认30秒）为1秒
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端收到最后一次心跳后等待时间上限（默认90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 2

#设置feign客户端的超时时间（openfeign默认支持ribbon)
ribbon:
  #建立连接的超时时间
  ReadTimeout: 5000
  #建立连接后，从服务器读取到可用资源的超时时间
  ConnectTimeout: 5000

#配置feign对应feignclient的日志级别
logging:
  level:
    com.wei.springcloud.service.PaymentFeignService: debug