server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态开启路由的功能，利用微服务名进行路由
      routes:
        - id: payment_lb #路由的id，没有固定的规则要求但是要求唯一，建议配合服务名设置
          uri: lb://cloud-payment-service  #路由匹配后进行服务的地址
          predicates:
            - Path=/payment/selfLoadBalance/showServerport   #断言，路径相匹配则进行路由

        - id: payment_lb2 #路由的id，没有固定的规则要求但是要求唯一，建议配合服务名设置
          uri: lb://cloud-payment-service  #路由匹配后进行服务的地址
          predicates:
            - Path=/payment/selfLoadBalance/showServerport   #断言，路径相匹配则进行路由
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
            - Cookie=chocolate, ch.p
            - Header=X-Request-Id, \d+
            - Host=**.somehost.org,**.anotherhost.org
            - Method=GET,POST
            - Query=green
            - RemoteAddr=192.168.1.1/24
            # 断言官网地址：https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#gateway-request-predicates-factories
          filters:
            - AddRequestHeader=X-Request-red, blue
              #过滤器官网地址：https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#gatewayfilter-factories

        - id: payment_routh #路由的id，没有固定的规则要求但是要求唯一，建议配合服务名设置
          uri: http://localhost:8001  #路由匹配后进行服务的地址
          predicates:
            - Path=/payment/getPaymentById/**   #断言，路径相匹配则进行路由

        - id: payment_routh2 #路由的id，没有固定的规则要求但是要求唯一，建议配合服务名设置
          uri: http://localhost:8001  #路由匹配后进行服务的地址
          predicates:
            - Path=/payment/testEnableDiscoveryClient   #断言，路径相匹配则进行路由

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #高可用版
  instance:
    instance-id: gateway9527
    prefer-ip-address: true
    #修改客户端向服务端发送心跳的周期时间（默认30秒）为1秒
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端收到最后一次心跳后等待时间上限（默认90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 2
