server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ze1bw0,7E[9V
    url: jdbc:mysql://192.168.59.131:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
  cloud:
    zookeeper:
      connect-string: 192.168.59.131:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wei.springcloud.entities
